### ISSUE TITLE
Petit problème à l'importation

### ISSUE THREAD

**Issue by VORKStephane** [deckard24/Warhammer-for-Sandbox#1]
Hello, 

J'ai installé le monde, mais il y a un problème lors de l'importation. En effet, le nom du fichier mentionné dans le JSON et le dossier téléchargé ne matchent pas, ce qui a pour conséquence que le monde n'apparaît pas lors de l'importation.

J'ai juste changé la valeur dans le JSON pour que cela fonctionne et tada :-)

Au passage, si tu as besoin d'aide, je suis dispo pour t'aider... Je peux pas me mettre à 100% sur le projet, mais j'aimerais que le système V2 sorte pour Foundry

Bien à toi,
Stéphane

**Comment by deckard24** [comment]
Salut à toi. 
Tout d'abord merci de t'interesser à mon système V2.
J'ai fait la modif. Pourras tu me confirmer le bon fonctionnement?
Pour ton info, ce soir, si tout va bien je sors une mise à jour de ce système intégrant notamment les armes, les armures et le jet de compétence 
Un immense merci pour ton aide. Une chose que tu peux faire pour m'aider est de tester de temps en temps le système afin de voir si cela fonctionne chez toi. Hésite pas à me remonter ce que tu trouves étrange par des issues.
Si tu as quelques connaissances en javascript je suis également preneur (je ne suis pas du tout codeur d'où le développement sur Sandbox)
Bien à toi
Bastien
